version: '3'

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16

services:
  nginx:
    image: nginx:latest
    ports:
      - "90:80"
    volumes:
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/balancer/nginx.conf:/etc/nginx/nginx.conf
      - ./service1/src:/etc/nginx/html/
    depends_on:
      - php
      - mysql
    networks:
      my_network:
        ipv4_address: 10.10.10.1
    # extra_hosts:
    #     - "service1:10.10.10.3"
    #     - "service2:10.10.10.4"

  # dummyhttp:
  #   container_name: dummyhttp
  #   build: ./dummyhttp
  #   ports:
  #     - "9090:8080"

  panel:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/panel/my.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      my_network:
        ipv4_address: 10.10.10.5

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    environment:
      DB_USER: 'root'
      DB_PASS: 'rootpass'
      DB_NAME: 'usecure'
      DB_HOST: mysql
    networks:
      - my_network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_DATABASE: 'usecure'
      MYSQL_USER: 'bez'
      MYSQL_PASSWORD: 'pass!1'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      my_network:
        ipv4_address: 10.10.10.2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - mysql
    networks:
      - my_network

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    volumes:
      - ./fastapi:/fastapi
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: rootpass
      MYSQL_USER: root
      MYSQL_DATABASE: usecure
      SECRET_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqQePvT7UdJl5FyaS+muZTyDAa/l2nMiIu9v7G/bhdHnRdljfE+P/NiJppnauUlk0e02GYfWhXE/4jWWH+Sw5MY0Comyb0ltBKjespF/U0YZJa7w6TE2qGKFx3+wcMbr8/rdZX6K0lJyfS5jRvvoOPHGuC2f8EuIkZqTXwWALRMG2iffhH0y9AWYcYykB2Y2wz9IY1CztYWPxGQzrwpX4UAH9rbNU1lp5NJkgJmrQjjjvSgMOr7WtoVi8Ec1uLRjXwk3eRJU4WvJbCXd5HfK3aka3pcFfM1gYSah08UBPue/8ie5isVjyCCd9ze09V0CucWtalkvswU+aY/bMsh5wxQIDAQAB"
    depends_on:
      - mysql
    networks:
      my_network:
        ipv4_address: 10.10.10.6

  service1:
    container_name: service1
    image: nginx:latest
    volumes:
      - ./service1/default.conf:/etc/nginx/conf.d/default.conf
      - ./service1/src:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      my_network:
        ipv4_address: 10.10.10.3
    ports:
      - "1234:80"

  service2:
    container_name: service2
    image: nginx:latest
    volumes:
      - ./service2/default.conf:/etc/nginx/conf.d/default.conf
      - ./service2/src:/var/www/html
    depends_on:
      - php
      - mysql
    ports:
      - "228:80"
    networks:
      my_network:
        ipv4_address: 10.10.10.4
